version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/lachs"
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo"
    directory: "/lachs_derive"
    schedule:
      interval: "daily"
